version: '3.9'

services:
  postgres:
    image: postgres:14.5-alpine
    ports:
      - ${DB_PORTS}
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - ${CACHE_PORTS}
    depends_on:
      - postgres
    volumes:
      - cache_data:/data

  file-server:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - ${FS_PORTS}
    env_file:
      - ./.env
    command: "alembic upgrade head && python3 src/main.py"
    volumes:
      - media_data:/app/media/
    depends_on:
      - postgres

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - ${WS_PORTS}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart:
      always
    depends_on:
      - file-server

volumes:
  postgres_data:
  cache_data:
  media_data: