"""01_initial-db

Revision ID: 806c2e03dfd3
Revises: 
Create Date: 2023-10-16 23:00:31.191837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806c2e03dfd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
